-- DROP DATABASE IF EXISTS flywaydemo;
-- CREATE DATABASE flywaydemo DEFAULT CHARSET utf8;
-- USE flywaydemo;

DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON (
  id int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar(100) not null,
  PRIMARY KEY (id)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;